apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    type: proxy
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080